services:
  - type: web
    name: email-sender
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/Email-sender-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.jdk
